[pytest]
addopts = --basetemp=pytest_tmp/basetemp
testpaths = tests
norecursedirs =
    .git
    .pytest_basetemp
    .pytest_cache
    .ruff_cache
    .manual_validation
    pytest_tmp
    pytest_run_tmp
    reports_pytest_tmp
    *-tests-*
